import type { Metadata, Viewport } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import { cookies } from "next/headers";
import { Analytics } from "@vercel/analytics/next";
import { WEBSITE } from "@/lib/legal";
import "./globals.css";

const schibsted = Schibsted_Grotesk({
  variable: "--font-schibsted",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// iOS standalone launch images (generated by scripts/gen-splash.mjs) — one
// per common iPhone viewport, themed, so the PWA opens onto brand colour
// instead of a white fill. Keep in sync with the script's VIEWPORTS list.
const SPLASH_VIEWPORTS: Array<[w: number, h: number, ratio: number]> = [
  [375, 667, 2],
  [414, 896, 2],
  [375, 812, 3],
  [390, 844, 3],
  [393, 852, 3],
  [402, 874, 3],
  [428, 926, 3],
  [430, 932, 3],
  [440, 956, 3],
];
const startupImage = SPLASH_VIEWPORTS.flatMap(([w, h, r]) =>
  (["light", "dark"] as const).map((scheme) => ({
    url: `/splash/splash-${w * r}x${h * r}-${scheme}.png`,
    media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait) and (prefers-color-scheme: ${scheme})`,
  }))
);

export const metadata: Metadata = {
  metadataBase: new URL(`https://${WEBSITE}`),
  title: "Beanlo — newborn tracker",
  description:
    "Track nappies, feeds and weight in the first days and weeks. A tracking aid, not medical advice.",
  appleWebApp: {
    capable: true,
    title: "beanlo",
    statusBarStyle: "default",
    startupImage,
  },
  icons: {
    icon: "/icons/icon-192.png",
    apple: "/icons/apple-touch-icon.png",
  },
};

export const viewport: Viewport = {
  // Media-query pair so the status bar / launch surface is correct in the
  // initial HTML — dark-mode users used to get a bright flash until a client
  // script patched the single light value after parse.
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#EDE9E1" },
    { media: "(prefers-color-scheme: dark)", color: "#16140f" },
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover", // draw into the iPhone safe areas; insets handled in CSS
};

// Keeps the status-bar colour in step with an EXPLICIT theme choice (the
// media-query metas above already handle system preference), and — for anyone
// whose preference is still only in localStorage (set before the cookie
// existed) — migrates it to the cookie so the server renders the right
// palette next time.
const THEME_SCRIPT = `(function(){try{var m=document.cookie.match(/(?:^|;\\s*)theme=(dark|light|system)/);var p=m?m[1]:localStorage.getItem('theme');if(!m&&(p==='dark'||p==='light'||p==='system')){document.cookie='theme='+p+'; path=/; max-age=31536000; samesite=lax';if(p==='dark'||p==='light')document.documentElement.setAttribute('data-theme',p);}if(p==='dark'||p==='light'){var c=p==='dark'?'#16140f':'#ede9e1';document.querySelectorAll('meta[name="theme-color"]').forEach(function(t){t.setAttribute('content',c);});}}catch(e){}})();`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Server-render the saved theme so the correct palette is present on first
  // paint — no flash and no dependency on a client script running in time.
  const pref = (await cookies()).get("theme")?.value;
  const dataTheme = pref === "dark" || pref === "light" ? pref : undefined;

  return (
    <html
      lang="en"
      className={`${schibsted.variable} h-full antialiased`}
      data-theme={dataTheme}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_SCRIPT }} />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
