import Foundation

// GENERATED by scripts/gen-who-swift.mjs from lib/whoGrowth.ts — do not edit.
// WHO length/height-for-age and head-circumference-for-age (cm). All rows
// have L = 1 (normally distributed).

enum WHOGrowth {
    enum Measure { case length, head }

    static let boysLengthWeekly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 49.8842, s: 0.03795),
        WHOWeight.LMS(t: 1, l: 1, m: 51.1152, s: 0.03723),
        WHOWeight.LMS(t: 2, l: 1, m: 52.3461, s: 0.03652),
        WHOWeight.LMS(t: 3, l: 1, m: 53.3905, s: 0.03609),
        WHOWeight.LMS(t: 4, l: 1, m: 54.3881, s: 0.0357),
        WHOWeight.LMS(t: 5, l: 1, m: 55.3374, s: 0.03534),
        WHOWeight.LMS(t: 6, l: 1, m: 56.2357, s: 0.03501),
        WHOWeight.LMS(t: 7, l: 1, m: 57.0851, s: 0.0347),
        WHOWeight.LMS(t: 8, l: 1, m: 57.8889, s: 0.03442),
        WHOWeight.LMS(t: 9, l: 1, m: 58.6536, s: 0.03416),
        WHOWeight.LMS(t: 10, l: 1, m: 59.3872, s: 0.03392),
        WHOWeight.LMS(t: 11, l: 1, m: 60.0894, s: 0.03369),
        WHOWeight.LMS(t: 12, l: 1, m: 60.7605, s: 0.03348),
        WHOWeight.LMS(t: 13, l: 1, m: 61.4013, s: 0.03329),
    ]
    static let boysLengthMonthly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 49.8842, s: 0.03795),
        WHOWeight.LMS(t: 1, l: 1, m: 54.7244, s: 0.03557),
        WHOWeight.LMS(t: 2, l: 1, m: 58.4249, s: 0.03424),
        WHOWeight.LMS(t: 3, l: 1, m: 61.4292, s: 0.03328),
        WHOWeight.LMS(t: 4, l: 1, m: 63.886, s: 0.03257),
        WHOWeight.LMS(t: 5, l: 1, m: 65.9026, s: 0.03204),
        WHOWeight.LMS(t: 6, l: 1, m: 67.6236, s: 0.03165),
        WHOWeight.LMS(t: 7, l: 1, m: 69.1645, s: 0.03139),
        WHOWeight.LMS(t: 8, l: 1, m: 70.5994, s: 0.03124),
        WHOWeight.LMS(t: 9, l: 1, m: 71.9687, s: 0.03117),
        WHOWeight.LMS(t: 10, l: 1, m: 73.2812, s: 0.03118),
        WHOWeight.LMS(t: 11, l: 1, m: 74.5388, s: 0.03125),
        WHOWeight.LMS(t: 12, l: 1, m: 75.7488, s: 0.03137),
        WHOWeight.LMS(t: 13, l: 1, m: 76.9186, s: 0.03154),
        WHOWeight.LMS(t: 14, l: 1, m: 78.0497, s: 0.03174),
        WHOWeight.LMS(t: 15, l: 1, m: 79.1458, s: 0.03197),
        WHOWeight.LMS(t: 16, l: 1, m: 80.2113, s: 0.03222),
        WHOWeight.LMS(t: 17, l: 1, m: 81.2487, s: 0.0325),
        WHOWeight.LMS(t: 18, l: 1, m: 82.2587, s: 0.03279),
        WHOWeight.LMS(t: 19, l: 1, m: 83.2418, s: 0.0331),
        WHOWeight.LMS(t: 20, l: 1, m: 84.1996, s: 0.03342),
        WHOWeight.LMS(t: 21, l: 1, m: 85.1348, s: 0.03376),
        WHOWeight.LMS(t: 22, l: 1, m: 86.0477, s: 0.0341),
        WHOWeight.LMS(t: 23, l: 1, m: 86.941, s: 0.03445),
        WHOWeight.LMS(t: 24, l: 1, m: 87.8161, s: 0.03479),
    ]
    static let girlsLengthWeekly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 49.1477, s: 0.0379),
        WHOWeight.LMS(t: 1, l: 1, m: 50.3298, s: 0.03742),
        WHOWeight.LMS(t: 2, l: 1, m: 51.512, s: 0.03694),
        WHOWeight.LMS(t: 3, l: 1, m: 52.4695, s: 0.03669),
        WHOWeight.LMS(t: 4, l: 1, m: 53.3809, s: 0.03647),
        WHOWeight.LMS(t: 5, l: 1, m: 54.2454, s: 0.03627),
        WHOWeight.LMS(t: 6, l: 1, m: 55.0642, s: 0.03609),
        WHOWeight.LMS(t: 7, l: 1, m: 55.8406, s: 0.03593),
        WHOWeight.LMS(t: 8, l: 1, m: 56.5767, s: 0.03578),
        WHOWeight.LMS(t: 9, l: 1, m: 57.2761, s: 0.03564),
        WHOWeight.LMS(t: 10, l: 1, m: 57.9436, s: 0.03552),
        WHOWeight.LMS(t: 11, l: 1, m: 58.5816, s: 0.0354),
        WHOWeight.LMS(t: 12, l: 1, m: 59.1922, s: 0.0353),
        WHOWeight.LMS(t: 13, l: 1, m: 59.7773, s: 0.0352),
    ]
    static let girlsLengthMonthly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 49.1477, s: 0.0379),
        WHOWeight.LMS(t: 1, l: 1, m: 53.6872, s: 0.0364),
        WHOWeight.LMS(t: 2, l: 1, m: 57.0673, s: 0.03568),
        WHOWeight.LMS(t: 3, l: 1, m: 59.8029, s: 0.0352),
        WHOWeight.LMS(t: 4, l: 1, m: 62.0899, s: 0.03486),
        WHOWeight.LMS(t: 5, l: 1, m: 64.0301, s: 0.03463),
        WHOWeight.LMS(t: 6, l: 1, m: 65.7311, s: 0.03448),
        WHOWeight.LMS(t: 7, l: 1, m: 67.2873, s: 0.03441),
        WHOWeight.LMS(t: 8, l: 1, m: 68.7498, s: 0.0344),
        WHOWeight.LMS(t: 9, l: 1, m: 70.1435, s: 0.03444),
        WHOWeight.LMS(t: 10, l: 1, m: 71.4818, s: 0.03452),
        WHOWeight.LMS(t: 11, l: 1, m: 72.771, s: 0.03464),
        WHOWeight.LMS(t: 12, l: 1, m: 74.015, s: 0.03479),
        WHOWeight.LMS(t: 13, l: 1, m: 75.2176, s: 0.03496),
        WHOWeight.LMS(t: 14, l: 1, m: 76.3817, s: 0.03514),
        WHOWeight.LMS(t: 15, l: 1, m: 77.5099, s: 0.03534),
        WHOWeight.LMS(t: 16, l: 1, m: 78.6055, s: 0.03555),
        WHOWeight.LMS(t: 17, l: 1, m: 79.671, s: 0.03576),
        WHOWeight.LMS(t: 18, l: 1, m: 80.7079, s: 0.03598),
        WHOWeight.LMS(t: 19, l: 1, m: 81.7182, s: 0.0362),
        WHOWeight.LMS(t: 20, l: 1, m: 82.7036, s: 0.03643),
        WHOWeight.LMS(t: 21, l: 1, m: 83.6654, s: 0.03666),
        WHOWeight.LMS(t: 22, l: 1, m: 84.604, s: 0.03688),
        WHOWeight.LMS(t: 23, l: 1, m: 85.5202, s: 0.03711),
        WHOWeight.LMS(t: 24, l: 1, m: 86.4153, s: 0.03734),
    ]
    static let boysHeadWeekly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 34.4618, s: 0.03686),
        WHOWeight.LMS(t: 1, l: 1, m: 35.1634, s: 0.03472),
        WHOWeight.LMS(t: 2, l: 1, m: 35.8649, s: 0.03258),
        WHOWeight.LMS(t: 3, l: 1, m: 36.5216, s: 0.03197),
        WHOWeight.LMS(t: 4, l: 1, m: 37.0926, s: 0.03148),
        WHOWeight.LMS(t: 5, l: 1, m: 37.601, s: 0.03107),
        WHOWeight.LMS(t: 6, l: 1, m: 38.0609, s: 0.03072),
        WHOWeight.LMS(t: 7, l: 1, m: 38.4824, s: 0.03041),
        WHOWeight.LMS(t: 8, l: 1, m: 38.8724, s: 0.03014),
        WHOWeight.LMS(t: 9, l: 1, m: 39.2368, s: 0.0299),
        WHOWeight.LMS(t: 10, l: 1, m: 39.5797, s: 0.02969),
        WHOWeight.LMS(t: 11, l: 1, m: 39.9033, s: 0.0295),
        WHOWeight.LMS(t: 12, l: 1, m: 40.2096, s: 0.02933),
        WHOWeight.LMS(t: 13, l: 1, m: 40.5008, s: 0.02918),
    ]
    static let boysHeadMonthly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 34.4618, s: 0.03686),
        WHOWeight.LMS(t: 1, l: 1, m: 37.2759, s: 0.03133),
        WHOWeight.LMS(t: 2, l: 1, m: 39.1285, s: 0.02997),
        WHOWeight.LMS(t: 3, l: 1, m: 40.5135, s: 0.02918),
        WHOWeight.LMS(t: 4, l: 1, m: 41.6317, s: 0.02868),
        WHOWeight.LMS(t: 5, l: 1, m: 42.5576, s: 0.02837),
        WHOWeight.LMS(t: 6, l: 1, m: 43.3306, s: 0.02817),
        WHOWeight.LMS(t: 7, l: 1, m: 43.9803, s: 0.02804),
        WHOWeight.LMS(t: 8, l: 1, m: 44.53, s: 0.02796),
        WHOWeight.LMS(t: 9, l: 1, m: 44.9998, s: 0.02792),
        WHOWeight.LMS(t: 10, l: 1, m: 45.4051, s: 0.0279),
        WHOWeight.LMS(t: 11, l: 1, m: 45.7573, s: 0.02789),
        WHOWeight.LMS(t: 12, l: 1, m: 46.0661, s: 0.02789),
        WHOWeight.LMS(t: 13, l: 1, m: 46.3395, s: 0.02789),
        WHOWeight.LMS(t: 14, l: 1, m: 46.5844, s: 0.02791),
        WHOWeight.LMS(t: 15, l: 1, m: 46.806, s: 0.02792),
        WHOWeight.LMS(t: 16, l: 1, m: 47.0088, s: 0.02795),
        WHOWeight.LMS(t: 17, l: 1, m: 47.1962, s: 0.02797),
        WHOWeight.LMS(t: 18, l: 1, m: 47.3711, s: 0.028),
        WHOWeight.LMS(t: 19, l: 1, m: 47.5357, s: 0.02803),
        WHOWeight.LMS(t: 20, l: 1, m: 47.6919, s: 0.02806),
        WHOWeight.LMS(t: 21, l: 1, m: 47.8408, s: 0.0281),
        WHOWeight.LMS(t: 22, l: 1, m: 47.9833, s: 0.02813),
        WHOWeight.LMS(t: 23, l: 1, m: 48.1201, s: 0.02817),
        WHOWeight.LMS(t: 24, l: 1, m: 48.2515, s: 0.02821),
    ]
    static let girlsHeadWeekly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 33.8787, s: 0.03496),
        WHOWeight.LMS(t: 1, l: 1, m: 34.5529, s: 0.03374),
        WHOWeight.LMS(t: 2, l: 1, m: 35.2272, s: 0.03251),
        WHOWeight.LMS(t: 3, l: 1, m: 35.843, s: 0.03231),
        WHOWeight.LMS(t: 4, l: 1, m: 36.3761, s: 0.03215),
        WHOWeight.LMS(t: 5, l: 1, m: 36.8472, s: 0.03202),
        WHOWeight.LMS(t: 6, l: 1, m: 37.2711, s: 0.03191),
        WHOWeight.LMS(t: 7, l: 1, m: 37.6584, s: 0.03182),
        WHOWeight.LMS(t: 8, l: 1, m: 38.0167, s: 0.03173),
        WHOWeight.LMS(t: 9, l: 1, m: 38.3516, s: 0.03166),
        WHOWeight.LMS(t: 10, l: 1, m: 38.6673, s: 0.03158),
        WHOWeight.LMS(t: 11, l: 1, m: 38.9661, s: 0.03152),
        WHOWeight.LMS(t: 12, l: 1, m: 39.2501, s: 0.03146),
        WHOWeight.LMS(t: 13, l: 1, m: 39.521, s: 0.0314),
    ]
    static let girlsHeadMonthly: [WHOWeight.LMS] = [
        WHOWeight.LMS(t: 0, l: 1, m: 33.8787, s: 0.03496),
        WHOWeight.LMS(t: 1, l: 1, m: 36.5463, s: 0.0321),
        WHOWeight.LMS(t: 2, l: 1, m: 38.2521, s: 0.03168),
        WHOWeight.LMS(t: 3, l: 1, m: 39.5328, s: 0.0314),
        WHOWeight.LMS(t: 4, l: 1, m: 40.5817, s: 0.03119),
        WHOWeight.LMS(t: 5, l: 1, m: 41.459, s: 0.03102),
        WHOWeight.LMS(t: 6, l: 1, m: 42.1995, s: 0.03087),
        WHOWeight.LMS(t: 7, l: 1, m: 42.829, s: 0.03075),
        WHOWeight.LMS(t: 8, l: 1, m: 43.3671, s: 0.03063),
        WHOWeight.LMS(t: 9, l: 1, m: 43.83, s: 0.03053),
        WHOWeight.LMS(t: 10, l: 1, m: 44.2319, s: 0.03044),
        WHOWeight.LMS(t: 11, l: 1, m: 44.5844, s: 0.03035),
        WHOWeight.LMS(t: 12, l: 1, m: 44.8965, s: 0.03027),
        WHOWeight.LMS(t: 13, l: 1, m: 45.1752, s: 0.03019),
        WHOWeight.LMS(t: 14, l: 1, m: 45.4265, s: 0.03012),
        WHOWeight.LMS(t: 15, l: 1, m: 45.6551, s: 0.03006),
        WHOWeight.LMS(t: 16, l: 1, m: 45.865, s: 0.02999),
        WHOWeight.LMS(t: 17, l: 1, m: 46.0598, s: 0.02993),
        WHOWeight.LMS(t: 18, l: 1, m: 46.2424, s: 0.02987),
        WHOWeight.LMS(t: 19, l: 1, m: 46.4152, s: 0.02982),
        WHOWeight.LMS(t: 20, l: 1, m: 46.5801, s: 0.02977),
        WHOWeight.LMS(t: 21, l: 1, m: 46.7384, s: 0.02972),
        WHOWeight.LMS(t: 22, l: 1, m: 46.8913, s: 0.02967),
        WHOWeight.LMS(t: 23, l: 1, m: 47.0391, s: 0.02962),
        WHOWeight.LMS(t: 24, l: 1, m: 47.1822, s: 0.02957),
    ]

    private static func tables(_ measure: Measure, isBoy: Bool) -> (weekly: [WHOWeight.LMS], monthly: [WHOWeight.LMS]) {
        switch (measure, isBoy) {
        case (.length, true): (boysLengthWeekly, boysLengthMonthly)
        case (.length, false): (girlsLengthWeekly, girlsLengthMonthly)
        case (.head, true): (boysHeadWeekly, boysHeadMonthly)
        case (.head, false): (girlsHeadWeekly, girlsHeadMonthly)
        }
    }

    private static func interp(_ table: [WHOWeight.LMS], _ t: Double) -> (l: Double, m: Double, s: Double) {
        if t <= table.first!.t { let r = table.first!; return (r.l, r.m, r.s) }
        if t >= table.last!.t { let r = table.last!; return (r.l, r.m, r.s) }
        var lower = table[0]
        for row in table.dropFirst() {
            if row.t >= t {
                let span = row.t - lower.t
                let f = span > 0 ? (t - lower.t) / span : 0
                return (lower.l + (row.l - lower.l) * f, lower.m + (row.m - lower.m) * f, lower.s + (row.s - lower.s) * f)
            }
            lower = row
        }
        let r = table.last!
        return (r.l, r.m, r.s)
    }

    private static func lmsFor(_ measure: Measure, isBoy: Bool, ageDays: Double) -> (l: Double, m: Double, s: Double) {
        let t = tables(measure, isBoy: isBoy)
        if ageDays <= 91 { return interp(t.weekly, ageDays / 7) }
        return interp(t.monthly, ageDays / WHOWeight.daysPerMonth)
    }

    /// Measurement (cm) at a z-score — one point on a centile curve.
    static func measureAtZ(_ measure: Measure, isBoy: Bool, ageDays: Double, z: Double) -> Double {
        let (l, m, s) = lmsFor(measure, isBoy: isBoy, ageDays: ageDays)
        let v = abs(l) < 1e-7 ? m * exp(s * z) : m * pow(1 + l * s * z, 1 / l)
        return (v * 10).rounded() / 10
    }

    /// The centile (0–100) a measurement sits on.
    static func centile(_ measure: Measure, isBoy: Bool, ageDays: Double, cm: Double) -> Double {
        let (l, m, s) = lmsFor(measure, isBoy: isBoy, ageDays: ageDays)
        let ratio = cm / m
        let z = abs(l) < 1e-7 ? log(ratio) / s : (pow(ratio, l) - 1) / (l * s)
        let t = 1 / (1 + 0.2316419 * abs(z))
        let d = 0.3989423 * exp(-z * z / 2)
        let p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.7814779 + t * (-1.821256 + t * 1.3302744))))
        return (z > 0 ? 1 - p : p) * 100
    }

    static let crossChecks: [(measure: Measure, isBoy: Bool, ageDays: Double, z: Double, cm: Double)] = [
        (measure: .length, isBoy: true, ageDays: 21, z: 0, cm: 53.4),
        (measure: .length, isBoy: true, ageDays: 150, z: -2.0537, cm: 61.4),
        (measure: .length, isBoy: true, ageDays: 400, z: 2.0537, cm: 82.1),
        (measure: .length, isBoy: false, ageDays: 21, z: 0, cm: 52.5),
        (measure: .length, isBoy: false, ageDays: 150, z: -2.0537, cm: 59.3),
        (measure: .length, isBoy: false, ageDays: 400, z: 2.0537, cm: 80.8),
        (measure: .head, isBoy: true, ageDays: 21, z: 0, cm: 36.5),
        (measure: .head, isBoy: true, ageDays: 150, z: -2.0537, cm: 40),
        (measure: .head, isBoy: true, ageDays: 400, z: 2.0537, cm: 49),
        (measure: .head, isBoy: false, ageDays: 21, z: 0, cm: 35.8),
        (measure: .head, isBoy: false, ageDays: 150, z: -2.0537, cm: 38.8),
        (measure: .head, isBoy: false, ageDays: 400, z: 2.0537, cm: 48),
    ]

    static func verify() -> Bool {
        for c in crossChecks where abs(measureAtZ(c.measure, isBoy: c.isBoy, ageDays: c.ageDays, z: c.z) - c.cm) > 0.11 {
            return false
        }
        return true
    }
}
