import Foundation

// GENERATED by scripts/gen-who-swift.mjs from lib/whoWeight.ts — do not edit
// by hand; regenerate after changing the web tables. WHO Child Growth
// Standards weight-for-age LMS parameters, the basis of the UK-WHO (red
// book) charts. A guide for parents, not a substitute for the plotted book.

enum WHOWeight {
    struct LMS { let t: Double; let l: Double; let m: Double; let s: Double }

    /// The nine centile lines printed on UK-WHO charts, with exact z-scores.
    static let ukCentiles: [(label: String, z: Double)] = [
        ("0.4", -2.6521), ("2", -2.0537), ("9", -1.3408), ("25", -0.6745),
        ("50", 0), ("75", 0.6745), ("91", 1.3408), ("98", 2.0537), ("99.6", 2.6521),
    ]

    // Monthly LMS, ages 0–24 completed months.
    static let boysMonthly: [LMS] = [
        LMS(t: 0, l: 0.3487, m: 3.3464, s: 0.14602),
        LMS(t: 1, l: 0.2297, m: 4.4709, s: 0.13395),
        LMS(t: 2, l: 0.197, m: 5.5675, s: 0.12385),
        LMS(t: 3, l: 0.1738, m: 6.3762, s: 0.11727),
        LMS(t: 4, l: 0.1553, m: 7.0023, s: 0.11316),
        LMS(t: 5, l: 0.1395, m: 7.5105, s: 0.1108),
        LMS(t: 6, l: 0.1257, m: 7.934, s: 0.10958),
        LMS(t: 7, l: 0.1134, m: 8.297, s: 0.10902),
        LMS(t: 8, l: 0.1021, m: 8.6151, s: 0.10882),
        LMS(t: 9, l: 0.0917, m: 8.9014, s: 0.10881),
        LMS(t: 10, l: 0.082, m: 9.1649, s: 0.10891),
        LMS(t: 11, l: 0.073, m: 9.4122, s: 0.10906),
        LMS(t: 12, l: 0.0644, m: 9.6479, s: 0.10925),
        LMS(t: 13, l: 0.0563, m: 9.8749, s: 0.10949),
        LMS(t: 14, l: 0.0487, m: 10.0953, s: 0.10976),
        LMS(t: 15, l: 0.0413, m: 10.3108, s: 0.11007),
        LMS(t: 16, l: 0.0343, m: 10.5228, s: 0.11041),
        LMS(t: 17, l: 0.0275, m: 10.7319, s: 0.11079),
        LMS(t: 18, l: 0.0211, m: 10.9385, s: 0.11119),
        LMS(t: 19, l: 0.0148, m: 11.143, s: 0.11164),
        LMS(t: 20, l: 0.0087, m: 11.3462, s: 0.11211),
        LMS(t: 21, l: 0.0029, m: 11.5486, s: 0.11261),
        LMS(t: 22, l: -0.0028, m: 11.7504, s: 0.11314),
        LMS(t: 23, l: -0.0083, m: 11.9514, s: 0.11369),
        LMS(t: 24, l: -0.0137, m: 12.1515, s: 0.11426),
    ]
    static let girlsMonthly: [LMS] = [
        LMS(t: 0, l: 0.3809, m: 3.2322, s: 0.14171),
        LMS(t: 1, l: 0.1714, m: 4.1873, s: 0.13724),
        LMS(t: 2, l: 0.0962, m: 5.1282, s: 0.13),
        LMS(t: 3, l: 0.0402, m: 5.8458, s: 0.12619),
        LMS(t: 4, l: -0.005, m: 6.4237, s: 0.12402),
        LMS(t: 5, l: -0.043, m: 6.8985, s: 0.12274),
        LMS(t: 6, l: -0.0756, m: 7.297, s: 0.12204),
        LMS(t: 7, l: -0.1039, m: 7.6422, s: 0.12178),
        LMS(t: 8, l: -0.1288, m: 7.9487, s: 0.12181),
        LMS(t: 9, l: -0.1507, m: 8.2254, s: 0.12199),
        LMS(t: 10, l: -0.17, m: 8.48, s: 0.12223),
        LMS(t: 11, l: -0.1872, m: 8.7192, s: 0.12247),
        LMS(t: 12, l: -0.2024, m: 8.9481, s: 0.12268),
        LMS(t: 13, l: -0.2158, m: 9.1699, s: 0.12283),
        LMS(t: 14, l: -0.2278, m: 9.387, s: 0.12294),
        LMS(t: 15, l: -0.2384, m: 9.6008, s: 0.12299),
        LMS(t: 16, l: -0.2478, m: 9.8124, s: 0.12303),
        LMS(t: 17, l: -0.2562, m: 10.0226, s: 0.12306),
        LMS(t: 18, l: -0.2637, m: 10.2315, s: 0.12309),
        LMS(t: 19, l: -0.2703, m: 10.4393, s: 0.12315),
        LMS(t: 20, l: -0.2762, m: 10.6464, s: 0.12323),
        LMS(t: 21, l: -0.2815, m: 10.8534, s: 0.12335),
        LMS(t: 22, l: -0.2862, m: 11.0608, s: 0.1235),
        LMS(t: 23, l: -0.2903, m: 11.2688, s: 0.12369),
        LMS(t: 24, l: -0.2941, m: 11.4775, s: 0.1239),
    ]
    // Weekly LMS for the steep first 13 weeks.
    static let boysWeekly: [LMS] = [
        LMS(t: 0, l: 0.3487, m: 3.3464, s: 0.14602),
        LMS(t: 1, l: 0.2776, m: 3.4879, s: 0.14483),
        LMS(t: 2, l: 0.2581, m: 3.7529, s: 0.14142),
        LMS(t: 3, l: 0.2442, m: 4.0603, s: 0.13807),
        LMS(t: 4, l: 0.2331, m: 4.3671, s: 0.13497),
        LMS(t: 5, l: 0.2237, m: 4.659, s: 0.13215),
        LMS(t: 6, l: 0.2155, m: 4.9303, s: 0.1296),
        LMS(t: 7, l: 0.2081, m: 5.1817, s: 0.12729),
        LMS(t: 8, l: 0.2014, m: 5.4149, s: 0.1252),
        LMS(t: 9, l: 0.1952, m: 5.6319, s: 0.1233),
        LMS(t: 10, l: 0.1894, m: 5.8346, s: 0.12157),
        LMS(t: 11, l: 0.184, m: 6.0242, s: 0.12001),
        LMS(t: 12, l: 0.1789, m: 6.2019, s: 0.1186),
        LMS(t: 13, l: 0.174, m: 6.369, s: 0.11732),
    ]
    static let girlsWeekly: [LMS] = [
        LMS(t: 0, l: 0.3809, m: 3.2322, s: 0.14171),
        LMS(t: 1, l: 0.2671, m: 3.3388, s: 0.146),
        LMS(t: 2, l: 0.2304, m: 3.5693, s: 0.14339),
        LMS(t: 3, l: 0.2024, m: 3.8352, s: 0.1406),
        LMS(t: 4, l: 0.1789, m: 4.0987, s: 0.13805),
        LMS(t: 5, l: 0.1582, m: 4.3476, s: 0.13583),
        LMS(t: 6, l: 0.1395, m: 4.5793, s: 0.13392),
        LMS(t: 7, l: 0.1224, m: 4.795, s: 0.13228),
        LMS(t: 8, l: 0.1065, m: 4.9959, s: 0.13087),
        LMS(t: 9, l: 0.0918, m: 5.1842, s: 0.12966),
        LMS(t: 10, l: 0.0779, m: 5.3618, s: 0.12861),
        LMS(t: 11, l: 0.0648, m: 5.5295, s: 0.1277),
        LMS(t: 12, l: 0.0525, m: 5.6883, s: 0.12691),
        LMS(t: 13, l: 0.0407, m: 5.8393, s: 0.12622),
    ]

    static let daysPerMonth = 30.4375

    /// Linear interpolation across a table at fractional index t.
    private static func interp(_ table: [LMS], _ t: Double) -> (l: Double, m: Double, s: Double) {
        if t <= table.first!.t { let r = table.first!; return (r.l, r.m, r.s) }
        if t >= table.last!.t { let r = table.last!; return (r.l, r.m, r.s) }
        var lower = table[0]
        for row in table.dropFirst() {
            if row.t >= t {
                let span = row.t - lower.t
                let f = span > 0 ? (t - lower.t) / span : 0
                return (
                    lower.l + (row.l - lower.l) * f,
                    lower.m + (row.m - lower.m) * f,
                    lower.s + (row.s - lower.s) * f
                )
            }
            lower = row
        }
        let r = table.last!
        return (r.l, r.m, r.s)
    }

    /// Weekly resolution through 13 weeks (steepest), monthly beyond.
    private static func lmsFor(isBoy: Bool, ageDays: Double) -> (l: Double, m: Double, s: Double) {
        if ageDays <= 91 {
            return interp(isBoy ? boysWeekly : girlsWeekly, ageDays / 7)
        }
        return interp(isBoy ? boysMonthly : girlsMonthly, ageDays / daysPerMonth)
    }

    /// Weight in grams at a z-score for sex + age — one point on a curve.
    static func weightAtZ(isBoy: Bool, ageDays: Double, z: Double) -> Double {
        let (l, m, s) = lmsFor(isBoy: isBoy, ageDays: ageDays)
        let kg = abs(l) < 1e-7 ? m * exp(s * z) : m * pow(1 + l * s * z, 1 / l)
        return (kg * 1000).rounded()
    }

    /// The centile (0–100) a weight sits on, via the inverse LMS transform.
    static func centile(isBoy: Bool, ageDays: Double, weightG: Double) -> Double {
        let (l, m, s) = lmsFor(isBoy: isBoy, ageDays: ageDays)
        let ratio = weightG / 1000 / m
        let z = abs(l) < 1e-7 ? log(ratio) / s : (pow(ratio, l) - 1) / (l * s)
        return normalCdf(z) * 100
    }

    /// Standard normal CDF (Zelen & Severo approximation).
    private static func normalCdf(_ z: Double) -> Double {
        let t = 1 / (1 + 0.2316419 * abs(z))
        let d = 0.3989423 * exp(-z * z / 2)
        let p = d * t * (0.3193815 + t * (-0.3565638 + t * (1.7814779 + t * (-1.821256 + t * 1.3302744))))
        return z > 0 ? 1 - p : p
    }

    /// Cross-checks computed by the generator with the web implementation —
    /// asserted in DEBUG so the two apps can never silently diverge.
    static let crossChecks: [(isBoy: Bool, ageDays: Double, z: Double, grams: Double)] = [
        (isBoy: true, ageDays: 14, z: 0, grams: 3753),
        (isBoy: true, ageDays: 45, z: -2.0537, grams: 3839),
        (isBoy: true, ageDays: 200, z: 2.0537, grams: 10159),
        (isBoy: true, ageDays: 500, z: 0.6745, grams: 11433),
        (isBoy: false, ageDays: 14, z: 0, grams: 3569),
        (isBoy: false, ageDays: 45, z: -2.0537, grams: 3536),
        (isBoy: false, ageDays: 200, z: 2.0537, grams: 9654),
        (isBoy: false, ageDays: 500, z: 0.6745, grams: 10768),
    ]
    static let centileChecks: [(isBoy: Bool, ageDays: Double, weightG: Double, pct: Double)] = [
        (isBoy: true, ageDays: 30, weightG: 4400, pct: 46.61514775044965),
        (isBoy: false, ageDays: 90, weightG: 5800, pct: 49.03626241133692),
    ]

    static func verify() -> Bool {
        for c in crossChecks where abs(weightAtZ(isBoy: c.isBoy, ageDays: c.ageDays, z: c.z) - c.grams) > 1 {
            return false
        }
        for c in centileChecks where abs(centile(isBoy: c.isBoy, ageDays: c.ageDays, weightG: c.weightG) - c.pct) > 0.1 {
            return false
        }
        return true
    }
}
